### ISSUE TITLE
`isEqual` for sets of sets?

### ISSUE THREAD

**Issue by ornamentist** [nodef/extra-set#7]
In set theoretic terms I believe these two sets should be equal:

```
{{1,2}} and {{2, 1}}
```

Where `{{1,2}}` is a set of a single set of two integers. In a Node module file this would be:

```
const set = await import('extra-set');

var x = new Set([1, 2]);
var xs = new Set([x]);
var y = new Set([2, 1]);
var ys = new Set([y]);

console.log(set.isEqual(xs, ys));
// returns false
```

Is the `isEqual` function effectively a shallow comparison?

**Comment by wolfram77** [comment]
Yes @ornamentist, you are right `isEqual()` is currently shallow. We can deep comparision version of its contents but it would require `O(n^2)` comparisions i think. To avoid that one solution i think could be to generate an `object.hashCode() Set` and use that for comparisions. I am not sure how the `deep-equal` package does this. I will look into this issue, you can check out [deep-equal](https://www.npmjs.com/package/deep-equal) in the mean time.

**Comment by ornamentist** [comment]
Thanks, will do.  And thanks for developing a really useful library.

**Comment by wolfram77** [comment]
@ornamentist Does it matter that JavaScript's Set does not do deep-equality check itself?

```javascript
var a = new Set([1, 2]);
var b = new Set([2, 1]);
var c = new Set();

c.add(a)
// Set(1) { Set(2) { 1, 2 } }

c.add(b)
// Set(2) { Set(2) { 1, 2 }, Set(2) { 2, 1 } }
```

**Comment by ornamentist** [comment]
Perhaps the reason that JavaScript's built-in `Set` type and many third party `Set` libraries can't have true sets is that equality and identity are just too flexible to make implementation worthwhile.
