### ISSUE TITLE
The var statement is deprecated

### ISSUE THREAD

**Issue by Qsppl** [nodef/extra-set#9]
When trying to use the library in ESM or strict mode, an error occurs:

![image](https://github.com/nodef/extra-set/assets/22717464/6bdbd7d9-1805-468c-bb55-fe21081abe68)

![image](https://github.com/nodef/extra-set/assets/22717464/66eacebc-9adc-4171-bafd-2af74d70faa4)

This problem will be solved if we replace all var statements with let

**Comment by wolfram77** [comment]
Which Node.js version do you use? I have the latest version, and don't observe this issue.

**Comment by Qsppl** [comment]
I am using a library on the site. The error is reproduced in firefox.

example: https://codepen.io/qsppl/pen/NWZPWdB?editors=0010

Although now it seems to me that the problem is in Firefox dev-tools.
It seems that it simply cannot correctly display the position of the operator that threw the error.

**Comment by Qsppl** [comment]
Yes, it's just a bug in Firefox dev-tools.
Here is the corrected example: https://codepen.io/qsppl/pen/xxobxXV?editors=0010

Sorry, I'm closing the error.
